### ISSUE TITLE
Add details to error when failed to create new material

### ISSUE THREAD

**Issue by Nuzhyn-Ivan** [uzuran/steel_sheet_calc-remastered-#29]
Would be nice to show user why cant add specification of material. Ideally - add some tooltips to each field or some other info, like - "X_size in mm"
![image](https://user-images.githubusercontent.com/9976493/210962922-4fefc56e-4091-4195-985e-a7b3dc1cb9be.png)

**Comment by uzuran** [comment]
Done.
