### ISSUE TITLE
Create function which write off material from the storage or add the material to storage.

### ISSUE THREAD

**Issue by uzuran** [uzuran/steel_sheet_calc-remastered-#30]
After we push the minus button or plus button we have been  write off material from the storage or add material back if mistake from user happen (users always write off material, if there mistake happen we always bring the material back to storage.). All changes have bean save to the car_wash.db file.

**Comment by Nuzhyn-Ivan** [comment]
Current logic:
write off amount(UI field between plus and minus btns) is  int only. No minus values. 
write off(UI field in materials table) - cant be minus

When press minus btn:
in storage = in storage - write off amount
write off = write off amount (previous write off amount just lost, its ok)
check if write off amount > in storage, notify user if so

When press plus btn:
in storage = in storage + write off amount
write off = write off - write off amount
check if write off amount >  write off then write off set to 0(its a way to allow user handle mistakes)
